name: release

on:
  workflow_dispatch:
  push:
    branches: ["main", "release-v*"]
    paths-ignore:
      - 'docs/**'
      - '**.md'

env:
  REGISTRY: ghcr.io
  BRANCH_NAME: ${{ github.base_ref || github.ref_name }}
jobs:
  release-please:
    runs-on: ubuntu-latest
    if: github.repository == 'opentoucan/freebird'
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
    steps:
    - name: set config file from branch
      run: |
        if [[ ${{ env.BRANCH_NAME }} == *main* ]]; then
          echo "CONFIG_FILE=release-please-config.json" >> $GITHUB_ENV
        else
          echo "CONFIG_FILE=release-please-config-hotfix.json" >> $GITHUB_ENV
        fi
    - uses: googleapis/release-please-action@v4
      id: release
      with:
        token: ${{ secrets.PAT }}
        config-file: ${{ env.CONFIG_FILE }}
        manifest-file: .release-please-manifest.json
        target-branch: ${{ github.ref_name }}

  docker-build:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/freebird
          tags: |
            type=semver,pattern=${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
            type=raw,value=latest

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # If it's a major or minor version change then cut a branch from the new tag
      - name: Branch from tag
        if: ${{ needs.release-please.outputs.patch }} != 0
        run: |
          git checkout -b release-v${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }} ${{ needs.release-please.outputs.tag_name }}
          git push -u origin ${{ needs.release-please.outputs.tag_name }}
